### ISSUE TITLE
pip install issue

### ISSUE THREAD

**Issue by Oreomeow** [arantonitis/pynat#7]
When I use `pip install pynat`, I get an error because I don't have `six` installed. It's not good for me to add `pynat` in `requirements.txt`. Can the developer please fix this issue?

**Comment by FoliageOwO** [comment]
just gotta a solution:

1. download the latest file of `six` (.tar.gz): [six](https://pypi.org/project/six/#files)
2. extract to any path you want
3. use command line, then do `$ cd six-xxx && python setup.py install`
4. do the same steps to install `pynat`: [pynat](https://pypi.org/project/pynat/#files)

**Comment by w311ang** [comment]
```bash
pip install --no-use-pep517 pynat
```

**Comment by brostosjoined** [comment]
```shell
C:\Users\rover>py -m pip install six
Requirement already satisfied: six in c:\users\rover\appdata\roaming\python\python311\site-packages (1.16.0)
C:\Users\rover>py -m pip install pynat
``` 
```python
Collecting pynat
  Using cached pynat-0.7.0.tar.gz (7.1 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "C:\Users\rover\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\rover\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\rover\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\rover\AppData\Local\Temp\pip-build-env-nrl2d_mo\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\rover\AppData\Local\Temp\pip-build-env-nrl2d_mo\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\rover\AppData\Local\Temp\pip-build-env-nrl2d_mo\overlay\Lib\site-packages\setuptools\build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\rover\AppData\Local\Temp\pip-build-env-nrl2d_mo\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 7, in <module>
        File "C:\Users\rover\AppData\Local\Temp\pip-install-wnbwzj7w\pynat_40a2a44d0c7b427aac56b2ccea4a792b\pynat.py", line 29, in <module>
          from six import text_type
      ModuleNotFoundError: No module named 'six'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by VaporTang** [comment]
Try installing six using anaconda navigator and then open a terminal in your environment and type "pip install pynat"

**Comment by jophy** [comment]
`pip install six`

`pip install setuptools wheel`

`pip install --no-use-pep517 pynat`

**Comment by Hetons** [comment]
或者直接给一版可用的 requirments.txt  注意python = 3.8
aiohappyeyeballs==2.4.4
aiohttp==3.10.11
aiohttp_socks==0.11.0
aiosignal==1.3.1
async-timeout==5.0.1
attrs==25.3.0
beautifulsoup4==4.14.3
blinker==1.8.2
certifi==2026.1.4
cffi==1.17.1
charset-normalizer==3.4.4
click==8.1.8
colorama==0.4.6
exceptiongroup==1.3.1
Flask==3.0.3
Flask-Cors==5.0.0
frozenlist==1.5.0
h11==0.16.0
idna==3.11
importlib_metadata==8.5.0
itsdangerous==2.2.0
Jinja2==3.1.6
MarkupSafe==2.1.5
multidict==6.1.0
outcome==1.3.0.post0
pillow==10.4.0
propcache==0.2.0
pycparser==2.23
pynat==0.7.0
PySocks==1.7.1
python-socks==2.8.0
PyYAML==6.0.3
requests==2.32.4
selenium==4.27.1
six==1.17.0
sniffio==1.3.1
sortedcontainers==2.4.0
soupsieve==2.7
trio==0.27.0
trio-websocket==0.12.2
typing_extensions==4.13.2
urllib3==2.2.3
websocket-client==1.8.0
Werkzeug==3.0.6
wsproto==1.2.0
yarl==1.15.2
zipp==3.20.2
